version: '3'
services:
  pg-master:
    image: postgres:9.6

    container_name: afs-${CONTAINER_POSTFIX:-default}-postgresql-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxx1234
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

    volumes:
      - "../pgdata:/var/lib/postgresql/data/pgdata"
  minio1:
    image: minio/minio:RELEASE.2019-04-09T01-22-30Z

    container_name: minio1-webserver-${CONTAINER_POSTFIX:-default}

    volumes:
      - ../minio_data:/data

    ports:
      - "9000:9000"

    environment:
      MINIO_ACCESS_KEY: minioxxxak
      MINIO_SECRET_KEY: minioxxxsk

    command: server /data

  webserver:
    image: seed-proj/afs
    build:
      context: .

    container_name: afs-${CONTAINER_POSTFIX:-default}
    links:
      - "pg-master:postgres"
      - "minio1:minio1"

    depends_on:
      - "pg-master"
      - "minio1"

    volumes:
      - ".:/usr/volumes/src/"

    command: bash docker-cmd.sh

    ports:
      - "443:443"
      - "80:80"
